{"timestamp": "2025-09-09T11:14:16.508898+00:00", "api_endpoint": "/api/rag_chat", "error": "No module named 'chromadb.telemetry.product.posthog'", "traceback": "Traceback (most recent call last):\n  File \"app.py\", line 87, in rag_chat\n  File \"langgraph/pregel/__init__.py\", line 1448, in invoke\n  File \"langgraph/pregel/__init__.py\", line 983, in stream\n  File \"langgraph/pregel/__init__.py\", line 1537, in _panic_or_proceed\n  File \"concurrent/futures/thread.py\", line 59, in run\n  File \"langgraph/pregel/retry.py\", line 72, in run_with_retry\n  File \"langchain_core/runnables/base.py\", line 2873, in invoke\n  File \"langgraph/utils.py\", line 95, in invoke\n  File \"rag_workflow.py\", line 155, in prepare_retrieval\n  File \"langchain_core/_api/deprecation.py\", line 203, in warn_if_direct_instance\n  File \"langchain_community/vectorstores/chroma.py\", line 122, in __init__\n  File \"chromadb/__init__.py\", line 274, in Client\n  File \"chromadb/api/client.py\", line 139, in __init__\n  File \"chromadb/api/client.py\", line 43, in __init__\n  File \"chromadb/api/client.py\", line 53, in _create_system_if_not_exists\n  File \"chromadb/config.py\", line 398, in instance\n  File \"chromadb/config.py\", line 447, in get_class\n  File \"importlib/__init__.py\", line 88, in import_module\n  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 1324, in _find_and_load_unlocked\nModuleNotFoundError: No module named 'chromadb.telemetry.product.posthog'\n"}
